### ISSUE TITLE
Make animation faster

### ISSUE THREAD

**Issue by marcioAlmada** [awamper/gpaste-integration#10]
The animations are too slow. Can we have a way to adjust the time in milliseconds?

**Comment by najamelan** [comment]
there is so in the options... I can't check right now, because the extension doesn't work anymore on gnome 3.18, but I'm pretty sure I speeded them up just by going into the options dialog.

**Comment by marcioAlmada** [comment]
![gpaste](https://cloud.githubusercontent.com/assets/227395/11152044/23cc7d58-8a0f-11e5-94b3-6703fcd90d57.png)

^ this is all I see, any clues?

**Comment by najamelan** [comment]
I do not have the same options dialog you have, but I open it by opening gnome tweak tools > extensions > gpaste, there is a cogwheel button for the options and there is a tab on there called animations which has speed settings. Maybe you don't have the latest version?

**Comment by marcioAlmada** [comment]
I'm gonna wait for the update, ty.
