### ISSUE TITLE
Not working with gnome 3.14

### ISSUE THREAD

**Issue by tupucula** [awamper/gpaste-integration#7]
Hello

Thanks for this useful extension. However, it seems that the recent version from git (tried it today) is not working with gnome 3.14. Is this a bug or is it at this point only usable with gnome 3.16?

Regards
Jana

**Comment by awamper** [comment]
master branch only for latest released GNOME Shell, you can use 3.14 branch.

**Comment by mcepl** [comment]
I did (install from https://extensions.gnome.org/extension/752/gpaste-integration/) and still when trying to get to open for example Settings panel I get:

```
TypeError: GPaste.SettingsUiWidget is not a constructor

Stack trace:
  GpasteIntegrationPrefsWidget<._get_gpaste_page@/home/matej/.local/share/gnome-shell/extensions/gpaste_integration@awamper.gmail.com/prefs.js:629
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  GpasteIntegrationPrefsWidget<._init@/home/matej/.local/share/gnome-shell/extensions/gpaste_integration@awamper.gmail.com/prefs.js:345
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  buildPrefsWidget@/home/matej/.local/share/gnome-shell/extensions/gpaste_integration@awamper.gmail.com/prefs.js:644
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:96
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1
```

**Comment by awamper** [comment]
Try to comment out lines 345, 363 in file /home/matej/.local/share/gnome-shell/extensions/gpaste_integration@awamper.gmail.com/prefs.js

**Comment by mcepl** [comment]
Yeah, that seems to help. But it seems kind of hackish. Isn’t there a more proper solution, or is this it and I should make a pull request with these two lines deleted?

**Comment by awamper** [comment]
I think i'll delete them in the next version.
